services:
  airflow:
    build: .
    image: jet_case_study:latest
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./dbt:/opt/airflow/dbt
      
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW_CONN_XKCD=sqlite:////opt/airflow/data/xkcd.db
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS=True
      - DBT_PROFILES_DIR=/opt/airflow/dbt
    command: airflow standalone