version: '3'
services:
  airflow:
    image: jet_case_study:latest
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data  
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW_CONN_XKCD=sqlite:////opt/airflow/data/xkcd.db
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS=True
    command: airflow standalone